---
title: "Data Analysis"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```


```{r}
library(readxl)
library(tidyverse)
library(leaflet)
```


## Data Preparation

*   Subset to ug/m3 and the three given chemicals only  

```{r}
project_id_list = read_csv("data/brooklyn_cvcp_list.csv")
alpha = read_csv("data/cleandata/alpha.csv") %>% distinct()
mixed = read_csv("data/cleandata/mixed.csv") %>% distinct()
phoenix = read_csv("data/cleandata/phoenix.csv") %>% distinct()
york_and_others = read_csv("data/cleandata/york_and_others.csv") %>% janitor::clean_names() %>% distinct()

## Alpha 

alpha_sub = alpha %>% 
  select(street_address, sample_id, parameter, result = ug_m3_results) %>% 
  filter(parameter %in% c("Benzene", "Toluene", "Ethylbenzene", "o-Xylene", "p/m-Xylene", "Trichloroethene", "Tetrachloroethene")) %>% 
  mutate(
    parameter = ifelse(parameter == "p/m-Xylene", "m/p-Xylene", parameter)
  )

alpha_sub = left_join(alpha_sub, select(project_id_list, project_id, street_address = name), 
                      by = "street_address") %>%
  mutate(project_id = ifelse(street_address == "75 Dupont Street", "17CVCP035K",
                             ifelse(street_address == "161 Harrison Avenue", "19CVCP022K",
                                    ifelse(street_address == "174 Kings Highway", "19CVCP021K",
                                           ifelse(street_address == "777 Glenmore Avenue", "19CVCP001K",
ifelse(street_address == "820 Glenmore Avenue", "18CVCP009K", project_id)))))) %>%
  select(project_id, street_address, sample_id, everything())

## Mixed

mixed_sub = mixed %>% 
  select(street_address, sample_id, parameter, result = ug_m3_results) %>% 
  filter(parameter %in% c("Benzene", "Toluene", "Ethylbenzene", "o-Xylene", "m,p-Xylene", "m/p-Xylene", "m&p-Xylene", "p/m-Xylene", "Trichloroethene", "Tetrachloroethene")) %>% 
  mutate(
    parameter = ifelse(parameter %in% c("m,p-Xylene", "m/p-Xylene", "m&p-Xylene", "p/m-Xylene"), "m/p-Xylene", parameter)
  )

mixed_sub = left_join(mixed_sub, select(project_id_list, project_id, street_address = name), 
                      by = "street_address") %>% 
  select(project_id, street_address, sample_id, everything())

mixed_sub = mixed_sub %>% 
  slice(-(29:35))

## Phoenix

phoenix_sub = phoenix %>% 
  separate(street_address, sep = "SV ", into = c("a", "b")) %>% 
  select(-a) %>% 
  select(street_address = b, sample_id, parameter, result = ug_m3_result) %>% 
  filter(parameter %in% c("Benzene", "Toluene", "Ethylbenzene", "o-Xylene", "m,p-Xylene", "Trichloroethene", "Tetrachloroethene")) %>% 
  mutate(
    parameter = ifelse(parameter == "m,p-Xylene", "m/p-Xylene", parameter)
  ) %>% distinct()

# phoenix_id = phoenix_sub %>% 
#   select(street_address) %>% 
#   distinct()
# 
# phoenix_id = left_join(phoenix_id, select(project_id_list, project_id, street_address = name), by = "street_address")
# 
# write_csv(phoenix_id, "data/cleandata/phoenix_id.csv")

phoenix_id = read_csv("data/cleandata/phoenix_id.csv")

phoenix_sub = left_join(phoenix_sub, phoenix_id, 
                      by = "street_address") %>% 
  select(project_id, street_address, sample_id, everything()) %>% distinct()

## York and Others

york_and_others_sub = york_and_others %>% 
  filter(units != "ppbv") %>% 
  select(project_id, street_address = street, sample_id = client_id, parameter, result = results) %>% 
  filter(parameter %in% c("Benzene", "Toluene", "Ethylbenzene", "m + p  Xylene", "m,p-Xylene", "m,p-Xylenes", "m/p-Xylene", "m&p-Xylene", "mp-Xylene", "o Xylene", "o-Xylene", "O-Xylene (1,2-Dimethylbenzene)", "o-Xylene_", "oXylene", "p- & m- Xylenes", "p- & m- Xylenes_", "p-&m-Xylenes", "Xylene (m&p)", "Xylene (o)", "Xylene (Ortho)", "Xylene (p,m)", "Xylene,o-", "Xylenes (m&p)", "Xylenes (o)", "Trichloroethene", "Tetrachloroethene")) %>% 
  mutate(
    parameter = ifelse(parameter %in% c("m + p  Xylene", "m,p-Xylene", "m,p-Xylenes", "m/p-Xylene", "m&p-Xylene", "mp-Xylene", "p- & m- Xylenes", "p- & m- Xylenes_", "p-&m-Xylenes", "Xylene (m&p)", "Xylene (p,m)", "Xylenes (m&p)"), "m/p-Xylene",
                       ifelse(parameter %in% c("o Xylene", "o-Xylene", "O-Xylene (1,2-Dimethylbenzene)", "o-Xylene_", "oXylene", "Xylene (o)", "Xylene (Ortho)", "Xylene,o-", "Xylenes (o)"), "o-Xylene", parameter)),
    result = as.character(result)
  )

bind = bind_rows(alpha_sub, mixed_sub, phoenix_sub, york_and_others_sub) %>% 
  distinct(project_id, street_address, sample_id, parameter, .keep_all = TRUE)
  
bind_wide = bind %>% 
  pivot_wider(
    names_from = parameter,
    values_from = result
  ) %>% 
select(project_id, street_address, sample_id, Benzene, Toluene, Ethylbenzene, `o-Xylene`, `m/p-Xylene`, Trichloroethene, Tetrachloroethene)

bind_wide_dup = bind_wide %>% 
  mutate(
    Benzene = as.numeric(Benzene),
    Toluene = as.numeric(Toluene),
    Ethylbenzene = as.numeric(Ethylbenzene),
    `o-Xylene` = as.numeric(`o-Xylene`),
    `m/p-Xylene` = as.numeric(`m/p-Xylene`),
    Trichloroethene = as.numeric(Trichloroethene),
    Tetrachloroethene = as.numeric(Tetrachloroethene)
  ) %>% 
  rowwise() %>% 
  mutate(
    BTEX = sum(across(Benzene:`m/p-Xylene`), na.rm = TRUE)
  )

BTEX = bind_wide_dup$BTEX

bind_wide$BTEX = BTEX
```

*   Fill in missing values for `project_no` and `address` from the summary data  

```{r}
summary_data = read_excel("data/data_from_M/Summary of SV data for Capstone_236 sites.xlsx") %>% 
  janitor::clean_names() %>% 
  fill(c("project_no", "address")) %>% 
  mutate(
    btex = as.numeric(btex)
  )

names(summary_data) = names(bind_wide)
```

*   Merge `project_id` with lat/long

```{r, eval = FALSE}
geocoding = read_excel("Geocoding ALL.xlsx") %>% 
  janitor::clean_names() %>% 
  select(-name, -note) %>% 
  select(name = address, everything())

geo_info = left_join(project_id_list,
                     geocoding,
                     by = "name")

# write_csv(geo_info, file = "data/geo_info.csv")
```

*   Get a final (Summary of 236 sites from M + extracted by ourselves) cleaned dataset with only the desired chemicals

```{r}
final_df = bind_rows(bind_wide, summary_data) %>% 
  mutate(
    BTEX = as.character(BTEX),
    BTEX = ifelse(BTEX == "0", NA_character_, BTEX),
    BTEX = ifelse(Benzene == "ND" & Toluene == "ND" & Ethylbenzene == "ND" & `o-Xylene` == "ND" & `m/p-Xylene` == "ND", "ND", BTEX)
  )

write_csv(final_df, "results/final_df.csv")
```


```{r}
final_df %>% 
  pivot_longer(
    Benzene:BTEX,
    names_to = "parameter", 
    values_to = "conc"
  ) %>% 
  filter(parameter %in% c("BTEX", "Trichloroethene", "Tetrachloroethene")) %>% 
  mutate(conc = as.numeric(conc)) %>% 
  group_by(parameter) %>% 
  summarise(
    min = min(conc, na.rm = TRUE),
    median = median(conc, na.rm = TRUE),
    max = max(conc, na.rm = TRUE)
  )
```


```{r}
geo_info = read_csv("data/geo_info.csv")

geo_info %>% 
  leaflet() %>% 
  addTiles() %>%
  setView(-73.97968, 40.703312, zoom = 12) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addCircleMarkers(~ longitude, ~ latitude, radius = 1)
```


## Extract Maximum for Each Site

```{r}
final_df = read_csv("results/final_df.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    trichloroethene = as.numeric(trichloroethene),
    tetrachloroethene = as.numeric(tetrachloroethene),
    btex = as.numeric(btex),
    project_id = ifelse(street_address == "264 North 10th Street", "12CBCP035K", project_id)
  )

geo_info = read_csv("data/geo_info.csv")

geo_new = read_excel("data/data_from_M/Site Characteristics for Capstone Students.xlsx") %>% 
  janitor::clean_names()

max_value = final_df %>% 
  filter(project_id != "11CBCP015K") %>% 
  group_by(project_id) %>%
  summarise(
    trichloroethene_max = max(trichloroethene, na.rm = T),
    tetrachloroethene_max = max(tetrachloroethene, na.rm = T),
    btex_max = max(btex, na.rm = T)
  ) %>% 
  mutate(
    trichloroethene_max = str_replace(trichloroethene_max, "\\-Inf", ""),
    tetrachloroethene_max = str_replace(tetrachloroethene_max, "\\-Inf", ""),
    btex_max = str_replace(btex_max, "\\-Inf", ""),
    trichloroethene_max = as.numeric(trichloroethene_max),
    tetrachloroethene_max = as.numeric(tetrachloroethene_max),
    btex_max = as.numeric(btex_max)
  )

gis_csv = left_join(max_value, select(geo_new, project_id, zip, latitude, longitude), by = "project_id")

# write_csv(gis_csv, "results/gis_df.csv")

gis_zipcode = gis_csv %>% 
  group_by(zip) %>% 
  summarise(
    trichloroethene_sum = sum(trichloroethene_max, na.rm = T),
    tetrachloroethene_sum = sum(tetrachloroethene_max, na.rm = T),
    btex_sum = sum(btex_max, na.rm = T)
  )

# write_csv(gis_zipcode, "results/gis_zipcode_df.csv")
```


## Binary Chem

```{r}
binary = read_csv("results/gis_df.csv") %>% 
  mutate(
    tce_binary = ifelse(trichloroethene_max >= 2, 1, 0),
    pce_binary = ifelse(tetrachloroethene_max >= 30, 1, 0),
    btex_binary = ifelse(btex_max >= 6130, 1, 0),
    tce_binary = ifelse(is.na(trichloroethene_max), 0, tce_binary),
    pce_binary = ifelse(is.na(tetrachloroethene_max), 0, pce_binary),
    btex_binary = ifelse(is.na(btex_max), 0, btex_binary)
  ) 

# %>% 
#   relocate(tce_binary, .after = trichloroethene_max) %>% 
#   relocate(pce_binary, .after = tetrachloroethene_max) %>% 
#   relocate(btex_binary, .after = btex_max)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

percentage_plot = binary %>% 
  pivot_longer(
    tce_binary:btex_binary,
    names_to = "chem",
    values_to = "indicator"
  ) %>% 
  mutate(
    chem = str_replace(chem, "\\_binary", ""),
    chem = str_to_upper(chem),
    indicator = ifelse(indicator == 1, ">= Health-based Concentrations", "< Health-based Concentrations")
  ) %>%
  group_by(chem, indicator) %>% 
  summarise(n = n()) %>%
  mutate(prop = n / sum(n)) %>%
  mutate(prop = round(100 * prop, 1)) %>%
  ggplot(aes(x = chem, y = prop, fill = indicator)) +
  geom_bar(position = "stack", stat = "identity", alpha = .7) +
  geom_text(aes(label = (prop)), position = position_stack(vjust = 0.5), size = 5.5, colour = "black") +
  scale_fill_manual(values = c("#619CFF", "#F8766D")) +
  labs(
    x = "", 
    y = "Percentage\n(%)",
    fill = ""
  ) +
  theme(
    axis.text.x = element_text(face = "bold", size = 14),
    axis.text.y = element_text(size = 10),
    axis.title.y = element_text(face = "bold"),
    legend.margin = margin(t = -20),
  )

ggsave(
  file = "results/percentage_plot.png",
  plot = percentage_plot,
  width = 6,
  height = 6,
  bg = "white",
  dpi = 500
)
```

