---
title: "data_clean_Sissi"
output: github_document
date: "2023-1-31"

---

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(dplyr)
library(lubridate)
library(openxlsx)
```

```{r}
df = 
  read_excel("./data/data_from_M/phoenix/SV 81 McGuinness Blvd.xlsx") %>% 
  janitor::clean_names()

```

```{r}



df1 <- df %>% 
  row_to_names(row_number = 5) %>% 
  clean_names() %>% 
  select(-(2:6), -8, -12, -14, -16, -19, -21) %>% #may change
  filter(if_any(ppbv_result, ~ !(.x %in% c("ppbv Result", NA)))) %>% 
   mutate(parameter = ifelse(ppbv_rl=="%", "% Bromofluorobenzene", parameter))

df1$date_time <- convertToDateTime(df1$date_time)

df2 <- df %>% 
  slice(c(3:4)) %>% #may change
  select(1,2) 


# Syntax using colnames()
colnames(df2)[1] = "id"
colnames(df2)[2] = "client_id"

#df3 <- df2 %>% 
#  separate(id, into = c("id", "address"), sep = "Project ID:       ") #may change

address <- strsplit(as.character(df2$id),'Project ID:       ') 
do.call(rbind, address)
df3 <- data.frame(df2$id, df2$client_id, do.call(rbind, address))

df3 <- df3 %>% 
  select(2,4) 

colnames(df3)[1] = "client_id"
colnames(df3)[2] = "address"


df4 <-df1 %>% 
    mutate(project_id = df3[2,1],
         client_id = df3[1,2]) %>% 
  select(project_id, client_id, everything())



#df4 <-df1 %>% 
#    mutate(project_id = df3[2,1],
#         client_id = df3[1,2],
 #        project_id = project_id$address,
 #        client_id = client_id$client_id) %>% 
 # select(project_id, client_id, everything())



```

```{r}
write_csv(df4, "./data/cleandata/phoenix/SV 81 McGuinness Blvd.csv")
```

