---
title: "york_test_ltc"
output: github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#library(rJava)
#library(tabulizer)
library(tidyverse)
library(readxl)
```

## First Chunck 

```{r}
1SV_153_Green_Street = read_excel("data/data_from_M/york/SV 153 Green Street.xlsx", 
                        range = "A6:Y110", col_names = FALSE) %>% 
  rename("CAS.No" = ...1, 
         "Parameter" = ...2,
         "Results" = ...11, 
         "Flag" = ...13, 
         "Units" = ...16,
         "LOQ" = ...19,
         "Dilution" = ...25) %>% 
  filter(!is.na(CAS.No)) %>% 
  select(c(CAS.No, Parameter, Results, Flag, Units, LOQ, Dilution)) %>% 
  mutate(Matrix = "SV", 
         Lab = "York",
         Street = "153 Green Street",
         Client_ID = "18E1222-01",
         Collection_date = "03/24/2018")

View(1SV_153_Green_Street)

```

## TEST FIRST 
```{r}
1SV_153_Green_Street <- read_excel("data/data_from_M/york/SV 153 Green Street.xlsx", 
                                    range = "A55:Y89", col_names = FALSE) %>% 
  rename("CAS.No" = ...1, 
         "Parameter" = ...2,
         "Results" = ...11, 
         "Flag" = ...13, 
         "Units" = ...16,
         "LOQ" = ...19,
         "Dilution" = ...25) %>% 
  filter(!is.na(CAS.No)) %>% 
  select(c(CAS.No, Parameter, Results, Flag, Units, LOQ, Dilution)) %>% 
  mutate(Matrix = "SV", 
         Lab = "York",
         Street = "153 Green Street",
         Client_ID = "18E1222-01",
         Collection_date = "03/24/2018")
```



## Second Chunck 

```{r}
SV_153_Green_Street_2 <- read_excel("data/data_from_M/york/SV 153 Green Street.xlsx", 
                                    range = "A55:Y89", col_names = FALSE) %>% 
  rename("CAS.No" = ...1, 
         "Parameter" = ...2,
         "Results" = ...11, 
         "Flag" = ...13, 
         "Units" = ...16,
         "LOQ" = ...19,
         "Dilution" = ...25) %>% 
  filter(!is.na(CAS.No)) %>% 
  select(c(CAS.No, Parameter, Results, Flag, Units, LOQ, Dilution)) %>% 
  mutate(Matrix = "SV", 
         Lab = "York",
         Street = "153 Green Street",
         Client_ID = "18E1222-01",
         Collection_date = "03/24/2018")
```

## Third Chunck 

```{r}
SV_153_Green_Street_3 <- read_excel("data/data_from_M/york/SV 153 Green Street.xlsx", range = "A101:Y131", col_names = FALSE) %>% 
  rename("CAS.No" = ...1, 
         "Parameter" = ...2,
         "Results" = ...11, 
         "Flag" = ...13, 
         "Units" = ...16,
         "LOQ" = ...19,
         "Dilution" = ...25) %>% 
  filter(!is.na(CAS.No)) %>% 
  select(c(CAS.No, Parameter, Results, Flag, Units, LOQ, Dilution)) %>% 
  mutate(Matrix = "SV", 
         Lab = "York",
         Street = "153 Green Street",
         Client_ID = "18E1222-01",
         Collection_date = "03/24/2018")
```

## Fourth Chunck 

```{r}
SV_153_Green_Street_4 <- read_excel("data/data_from_M/york/SV 153 Green Street.xlsx", range = "A153:Y173", col_names = FALSE) %>% 
  rename("CAS.No" = ...1, 
         "Parameter" = ...2,
         "Results" = ...11, 
         "Flag" = ...13, 
         "Units" = ...16,
         "LOQ" = ...19,
         "Dilution" = ...25) %>% 
  filter(!is.na(CAS.No)) %>% 
  select(c(CAS.No, Parameter, Results, Flag, Units, LOQ, Dilution)) %>% 
  mutate(Matrix = "SV", 
         Lab = "York",
         Street = "153 Green Street",
         Client_ID = "18E1222-01",
         Collection_date = "03/24/2018")
```

## Fifth Chunck 

```{r}
SV_153_Green_Street_4 <- read_excel("data/data_from_M/york/SV 153 Green Street.xlsx", range = "A153:Y173", col_names = FALSE) %>% 
  rename("CAS.No" = ...1, 
         "Parameter" = ...2,
         "Results" = ...11, 
         "Flag" = ...13, 
         "Units" = ...16,
         "LOQ" = ...19,
         "Dilution" = ...25) %>% 
  filter(!is.na(CAS.No)) %>% 
  select(c(CAS.No, Parameter, Results, Flag, Units, LOQ, Dilution)) %>% 
  mutate(Matrix = "SV", 
         Lab = "York",
         Street = "153 Green Street",
         Client_ID = "18E1222-01",
         Collection_date = "03/24/2018")
```
